Update patch set 2
Patch Set 2:

Breaks build?!

packages/apps/Dialer/../InCallUI/src/com/android/incallui/ContactInfoCache.java:183: cannot find symbol
symbol  : variable ReverseLookupThread
location: class com.android.incallui.ContactInfoCache
                    ReverseLookupThread.performLookup(mContext, cacheEntry.number, listener);
                    ^

Patch-set: 2
Reviewer: Jon Mooney <5058@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0